"""empty message

Revision ID: 0ebde8896457
Revises: 385895141647
Create Date: 2024-08-01 19:55:34.331770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ebde8896457'
down_revision: Union[str, None] = '385895141647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cover_letter', 'type',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user_resume', 'version',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_resume', 'version',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_cover_letter', 'type',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
