"""empty message

Revision ID: 139f54c768d3
Revises: 
Create Date: 2024-07-27 16:49:07.845219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139f54c768d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('birth', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('disabled_type', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('disabled_level', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('issued_date', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('expiration_period', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('signed_date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_index('id_UNIQUE', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('id_UNIQUE', 'users', ['id'], unique=True)
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'signed_date')
    op.drop_column('users', 'expiration_period')
    op.drop_column('users', 'issued_date')
    op.drop_column('users', 'address')
    op.drop_column('users', 'disabled_level')
    op.drop_column('users', 'disabled_type')
    op.drop_column('users', 'birth')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
