"""empty message

Revision ID: 385895141647
Revises: 4a763ea139a3
Create Date: 2024-08-01 19:24:30.859359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '385895141647'
down_revision: Union[str, None] = '4a763ea139a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cover_letter', 'content',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cover_letter', 'content',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###
