"""empty message

Revision ID: 6adc3e7370e1
Revises: 8ba14cc6e998
Create Date: 2024-07-31 23:39:21.559182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6adc3e7370e1'
down_revision: Union[str, None] = '8ba14cc6e998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('work_experience', sa.String(length=50), nullable=False))
    op.drop_column('notices', 'career')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('career', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('notices', 'work_experience')
    # ### end Alembic commands ###
