"""empty message

Revision ID: 705ab3e18f6f
Revises: 6adc3e7370e1
Create Date: 2024-08-01 11:04:27.168770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705ab3e18f6f'
down_revision: Union[str, None] = '6adc3e7370e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recommand_job_1', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('recommand_job_2', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('recommand_job_3', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recommand_job_3')
    op.drop_column('users', 'recommand_job_2')
    op.drop_column('users', 'recommand_job_1')
    # ### end Alembic commands ###
