"""empty message

Revision ID: 84737a3d5c71
Revises: 
Create Date: 2024-07-27 15:46:07.550737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84737a3d5c71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='members')
    op.drop_table('members')
    op.add_column('users', sa.Column('updated_date', sa.DateTime(), nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'expiration_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expiration_period', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.drop_column('users', 'updated_date')
    op.create_table('members',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('birth', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('disabled_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('disabled_level', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address', mysql.TEXT(), nullable=False),
    sa.Column('issued_date', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('expiration_period', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('signed_date', mysql.DATETIME(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'members', ['email'], unique=True)
    # ### end Alembic commands ###
