"""empty message

Revision ID: 8ba14cc6e998
Revises: d4d18640a92f
Create Date: 2024-07-31 23:13:48.578646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ba14cc6e998'
down_revision: Union[str, None] = 'd4d18640a92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('career', sa.String(length=50), nullable=False),
    sa.Column('education', sa.String(length=50), nullable=False),
    sa.Column('address1', sa.Text(), nullable=False),
    sa.Column('address2', sa.Text(), nullable=False),
    sa.Column('working_hour', sa.String(length=50), nullable=False),
    sa.Column('deadline', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('before_notices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('before_notices',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('office', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('career', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('education', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address', mysql.TEXT(), nullable=False),
    sa.Column('register', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('deadline', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('contract', mysql.TEXT(), nullable=False),
    sa.Column('working_day', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('work_week', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('notices')
    # ### end Alembic commands ###
