"""empty message

Revision ID: ec2fccb05708
Revises: 2d3abcc37a8b
Create Date: 2024-07-28 02:01:42.728184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec2fccb05708'
down_revision: Union[str, None] = '2d3abcc37a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_resume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_resume',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('version', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('content', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
