"""empty message

Revision ID: 1b1e898e96eb
Revises: d40724b122e0
Create Date: 2024-07-13 00:29:36.575309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1e898e96eb'
down_revision: Union[str, None] = 'd40724b122e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uesr', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'uesr', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uesr', type_='unique')
    op.drop_column('uesr', 'email')
    # ### end Alembic commands ###
