"""empty message

Revision ID: 605329bbbd8f
Revises: 7598cfbb9830
Create Date: 2024-07-18 02:05:44.931491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605329bbbd8f'
down_revision: Union[str, None] = '7598cfbb9830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('birth', sa.String(length=10), nullable=False),
    sa.Column('disabled_type', sa.String(length=50), nullable=False),
    sa.Column('disabled_level', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('issued_date', sa.String(length=10), nullable=False),
    sa.Column('expiration_period', sa.String(length=10), nullable=False),
    sa.Column('signed_date', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
