"""empty message

Revision ID: d40724b122e0
Revises: d6d56dc5e858
Create Date: 2024-07-13 00:25:37.770448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40724b122e0'
down_revision: Union[str, None] = 'd6d56dc5e858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uesr', sa.Column('password', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'uesr', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uesr', type_='unique')
    op.drop_column('uesr', 'password')
    # ### end Alembic commands ###
