"""empty message

Revision ID: d6d56dc5e858
Revises: 4c365e550fae
Create Date: 2024-07-13 00:23:44.419419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d56dc5e858'
down_revision: Union[str, None] = '4c365e550fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uesr', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'uesr', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uesr', type_='unique')
    op.drop_column('uesr', 'password')
    # ### end Alembic commands ###
